language: java
jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7
before_script:
  - wget "https://github.com/n1k0/casperjs/tarball/1.0.2" -O casper.tar.gz
  - tar -xvzf casper.tar.gz
  - mv $(find -name "n1k0-casperjs*" -type d) casperjs
  - export PATH=$PATH:$(pwd)/casperjs/bin
