language: java
jdk:
  - oraclejdk5
  - oraclejdk6
  - oraclejdk7
  - openjdk5
  - openjdk6
  - openjdk7
before_script:
  - wget "https://github.com/n1k0/casperjs/tarball/1.0.2" -O casper.tar.gz
  - tar -xvzf casper.tar.gz
  - find -name "n1k0-casperjs*" -type d -exec mv -v {} casperjs \;
  - export PATH=$PATH:$(pwd)/casperjs/bin
